### ISSUE TITLE
cluster-assign-roles.sh failed during the automated_install.sh

### ISSUE THREAD

**Issue by leochen4891** [bloomberg/chef-bach#1000]
```
Recipe: bcpc-hadoop::core_site
  * ruby_block[node.run_state[:core_site_generated_values]] action run
    
    ================================================================================
    Error executing action `run` on resource 'ruby_block[node.run_state[:core_site_generated_values]]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/bcpc-hadoop/recipes/core_site.rb:80:in `block (2 levels) in from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc-hadoop/recipes/core_site.rb
    
     78: ruby_block 'node.run_state[:core_site_generated_values]' do
     79:   block do
     80:     mounts = node.run_state[:bcpc_hadoop_disks][:mounts]
     81:     directory_values =
     82:       {
     83:        'mapreduce.cluster.local.dir' =>
     84:          mounts.map{ |d| "file:///disk/#{d}/yarn/mapred-local" }.join(','),
     85:        'yarn.nodemanager.log-dirs' =>
     86:          mounts.map{ |d| "file:///disk/#{d}/yarn/logs" }.join(','),
     87:       }
     88:     node.run_state[:core_site_generated_values].merge!(directory_values)
     89:     node.run_state[:core_site_generated_values].merge!(core_site_values)
     90:   end
     91: end
     92: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc-hadoop/recipes/core_site.rb:78:in `from_file'
    
    ruby_block("node.run_state[:core_site_generated_values]") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "node.run_state[:core_site_generated_values]"
      declared_type :ruby_block
      cookbook_name "bcpc-hadoop"
      recipe_name "core_site"
      block #<Proc:0x000000078dc730@/var/chef/cache/cookbooks/bcpc-hadoop/recipes/core_site.rb:79>
    end
```

**Comment by pu239ppy** [comment]
This was duplicated and fixed in #1002
