### ISSUE TITLE
unable to build cluster on ubuntu 14.04

### ISSUE THREAD

**Issue by saumilmayani** [bloomberg/chef-bach#1019]
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Steps 
```
vboxmanage list dhcpservers
sudo vboxmanage list dhcpservers
sudo pkill -f VBox
git clone https://github.com/bloomberg/chef-bach.git
mv chef-bach/ chef-bcpc
cd chef-bcpc/
git branch

git remote add ipxe_delete https://github.com/cbaenziger/chef-bach.git
git remote -v
git pull ipxe_delete ipxe_delete

==========
remote: Counting objects: 43, done.
remote: Total 43 (delta 30), reused 30 (delta 30), pack-reused 13
Unpacking objects: 100% (43/43), done.
From https://github.com/cbaenziger/chef-bach
 * branch            ipxe_delete -> FETCH_HEAD
 * [new branch]      ipxe_delete -> ipxe_delete/ipxe_delete
Auto-merging vbox_create.sh
CONFLICT (content): Merge conflict in vbox_create.sh
Automatic merge failed; fix conflicts and then commit the result.
==========

vi vbox_create.sh

<<<<<<< HEAD
# populate the VM_LIST array from cluster.txt
# HACK: This is called prior to cluster.txt modification
code_to_produce_vm_list="
require './lib/cluster_data.rb';
include BACH::ClusterData;
cp=ENV.fetch('BACH_CLUSTER_PREFIX', '');
cp += '-' unless cp.empty?;
vms = parse_cluster_txt(File.readlines('cluster.txt'))
puts vms.map{|e| cp + e[:hostname]}.join(' ')
"
VM_LIST=( $(ruby -e "$code_to_produce_vm_list") )
export VM_LIST

=======
code_to_produce_vm_list="
require './lib/cluster_data.rb';
include BACH::ClusterData;
cp=ENV.fetch('CLUSTER_PREFIX', '');
cp += '-' unless cp.empty?;
vms = parse_cluster_txt(File.readlines(File.join(
  'stub-environment','${CLUSTER_TYPE,,}_cluster.txt')))
puts vms.map{|e| cp + e[:hostname]}.join(' ')
"
VM_LIST=( $(ruby -e "$code_to_produce_vm_list") )
>>>>>>> accd71de866ee551e8c0a2526db89cd022b880c3

<<<<<<< HEAD
  # BOOTSTRAP_NAME is exported by automated_install.sh
  bootstrap_interfaces=($($VBM showvminfo ${BOOTSTRAP_NAME} \
=======

  bootstrap_interfaces=($($VBM showvminfo ${BACH_CLUSTER_PREFIX}-bcpc-bootstrap \
>>>>>>> accd71de866ee551e8c0a2526db89cd022b880c3

git status
git add vbox_create.sh
git commit
git status


./tests/automated_install.sh
==========

./tests/automated_install.sh: line 31: [: !=: unary operator expected
#### Setup configuration files
Usage: nmcli connection { COMMAND | help }
  COMMAND := { list | status | up | down | delete }

  list [id <id> | uuid <id>]
  status [id <id> | uuid <id> | path <path>]
  up id <id> | uuid <id> [iface <iface>] [ap <BSSID>] [--nowait] [--timeout <timeout>]
  down id <id> | uuid <id>
  delete id <id> | uuid <id>

Error: 'con' command 'show' is not valid.
./tests/edit_environment.rb:77:in `get_name_server': No DNS server provided, and none found in local DHCP leases (RuntimeError)
	from ./tests/edit_environment.rb:82:in `<main>'

==========
```

**Comment by cbaenziger** [comment]
Hi Saumil, are you submitting a patch or reporting that we no-longer work with 14.04? I do see our README does not specify an Ubuntu version and our [bootstrap.md](bootstrap.md) file is quite crufty talking of 12.04 still. All our test hypervisors are now 16.04 however.

**Comment by saumilmayani** [comment]
hi @cbaenziger  sure, I am upgrading my hypervisors to 16.04. will keep posted.

**Comment by saumilmayani** [comment]
Hi @cbaenziger On OS Ubuntu 16.04.3 LTS, I get the following exception:

```
==> bcpc-bootstrap: stdin: is not a tty
+ popd
~/Downloads/bbg/chef-bcpc
+ python_to_find_bootstrap_ip='import json; j = json.load(file('\''./environments/Test-Laptop.json'\'')); print j['\''override_attributes'\'']['\''bcpc'\'']['\''bootstrap'\'']['\''server'\'']'
++ python -c 'import json; j = json.load(file('\''./environments/Test-Laptop.json'\'')); print j['\''override_attributes'\'']['\''bcpc'\'']['\''bootstrap'\'']['\''server'\'']'
+ BOOTSTRAP_IP=10.0.101.3
+ create_cluster_VMs
+ oifs='
'
+ IFS='
'
+ bootstrap_interfaces=($($VBM showvminfo ${BACH_CLUSTER_PREFIX}-bcpc-bootstrap     --machinereadable |     egrep '^hostonlyadapter[0-9]=' |     sort |     sed -e 's/.*=//' -e 's/"//g'))
++ VBoxManage showvminfo -bcpc-bootstrap --machinereadable
++ egrep '^hostonlyadapter[0-9]='
++ sort
++ sed -e 's/.*=//' -e 's/"//g'
Oracle VM VirtualBox Command Line Management Interface Version 5.0.40
(C) 2005-2017 Oracle Corporation
All rights reserved.

Usage:

VBoxManage showvminfo       <uuid|vmname> [--details]
                            [--machinereadable]
VBoxManage showvminfo       <uuid|vmname> --log <idx>

VBoxManage: error: Unknown option: -bcpc-bootstrap
+ IFS='
'
./vbox_create.sh: line 174: bootstrap_interfaces[0]: Need a Virtualbox network 1 for the bootstrap
```

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by saumilmayani** [comment]
I got passed the initial issue / stage with following combination of bits:

Oracle VM VirtualBox Manager 5.1.30
Vagrant 2.0.0
chefdk_2.3.4-1_amd64.deb 

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
git clone https://github.com/bloomberg/chef-bach.git
git branch
```
* master
```

**Comment by saumilmayani** [comment]
Will Close this issue. as I see the vms created.
bcpc-bootstrap
bcpc-vm1
bcpc-vm2
bcpc-vm3
