### ISSUE TITLE
NameError In Slider Recipe

### ISSUE THREAD

**Issue by rashidaligee** [bloomberg/chef-bach#1087]
The build failed on `bcpc-vm3`

Possibly related to #1063 

```
 ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/bcpc-hadoop/recipes/datanode.rb
  ================================================================================
  
  NameError
  ---------
  No resource, method, or local variable named `zk_hosts' for `Chef::Recipe "slider"'
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/bcpc-hadoop/recipes/slider.rb:17:in `from_file'
    /var/chef/cache/cookbooks/bcpc-hadoop/recipes/datanode.rb:325:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/bcpc-hadoop/recipes/slider.rb:
  
   10:  
   11:  hdp_select('slider-client', node[:bcpc][:hadoop][:distribution][:active_release])
   12:  
   13:  site_xml = node.default[:bcpc][:hadoop][:yarn][:site_xml]
   14:  
   15:  slider_properties = {
   16:    'hadoop.registry.zk.quorum' =>
   17>>     zk_hosts.map{ |h| float_host(h[:hostname]) +
   18:        ":#{node[:bcpc][:hadoop][:zookeeper][:port]}"}
   19:      .join(','),
   20:    'hadoop.registry.rm.enabled' => true
   21:  }
   22:  site_xml.merge!(slider_properties)
   23:  
   24:  
   25:  node.default['bcpc']['hadoop']['slider']['env'] = {}
   26:  node.default['bcpc']['hadoop']['slider']['env'].tap do |slider_env|
  
  Platform:
  ---------
  x86_64-linux
  
  
  Running handlers:
  Running handlers complete
  Chef Client failed. 16 resources updated in 01 minutes 02 seconds
bundler: failed to load command: ./cluster_assign_roles.rb (./cluster_assign_roles.rb)
RuntimeError: bcpc-vm3.bcpc.example.com: Got failed status 1 from chef run!
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:170:in `chef_node_with_runlist'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:256:in `block in install_hadoop'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:254:in `each'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:254:in `install_hadoop'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:490:in `car_cli'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:498:in `<top (required)>'
```

**Comment by pu239ppy** [comment]
Looks like I neglected to pull in a very last commit for the final test.  Looking at the code now, this would have never worked. Rebased on master and building.
