### ISSUE TITLE
HBASE Issue frequently encountered during C-A-R

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#1096]
I am frequently seeing this error when chefing HBase Master

````
  * service[hbase-master] action start
    - start service service[hbase-master]
  * ruby_block[handle_prev_hbase_master_restart_failure] action create

    ================================================================================
    Error executing action `create` on resource 'ruby_block[handle_prev_hbase_master_restart_failure]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:341:in `process_restarted_after_failure?'
    /var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:38:in `block (3 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb

     32:     ruby_block "handle_prev_#{params[:service_name].gsub('-','_')}_restart_failure" do
     33:       block do
     34:         Chef::Log.info "Need to restart #{params[:service_name]} since it failed during the previous run. Another node's restart process failure is a possible reason"
     35:       end
     36:       action :create
     37:       only_if { node[:bcpc][:hadoop][params[:service_name].gsub('-','_').to_sym][:restart_failed] and
     38:               !process_restarted_after_failure?(node[:bcpc][:hadoop][params[:service_name].gsub('-','_').to_sym][:restart_failed_time],"#{params[:process_identifier]}")}
     39:     end
     40:     #
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:32:in `block in from_file'

    ruby_block("handle_prev_hbase_master_restart_failure") do
      params {:service_name=>"hbase-master", :dependencies=>["template[/etc/hbase/conf/hadoop-metrics2-hbase.properties]", "template[/etc/hbase/conf/hbase-site.xml]", "template[/etc/hbase/conf/hbase-env.sh]", "template[/etc/hbase/conf/hbase-policy.xml]", "template[/etc/hadoop/conf/log4j.properties]", "file[/etc/hadoop/conf/ldap-conn-pass.txt]", "template[/etc/hadoop/conf/hdfs-site.xml]", "template[/etc/hadoop/conf/core-site.xml]", "bash[hdp-select hbase-regionserver]", "user_ulimit[hbase]", "log[jdk-version-changed]", "bash[hdp-select hbase-master]"], :process_identifier=>"org.apache.hadoop.hbase.master.HMaster", :name=>"hbase-master"}
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "handle_prev_hbase_master_restart_failure"
      declared_type :ruby_block
      cookbook_name "bcpc-hadoop"
      recipe_name "hbase_master"
      block #<Proc:0x0000000ac37260@/var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:33>
      only_if { #code block }
    end

    Platform:
    ---------
    x86_64-linux
````

/var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:38
````
 !process_restarted_after_failure?(node[:bcpc][:hadoop][params[:service_name].gsub('-','_').to_sym][:restart_failed_time],"#{params[:process_identifier]}")}
````
/var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:341
````
341     if start_time.nil? && (Time.parse(restart_failure_time).to_i < Time.parse(start_time).to_i)
````

**Comment by pu239ppy** [comment]
Seems as if in https://github.com/bloomberg/chef-bach/commit/a3c0d112c3a29c9d17096933fb4c7c956f2079ea, the expression changed from 
`if start_time? && (Time.parse(restart_failure_time).to_i < Time.parse(start_time).to_i)` to `if start_time.nil? && (Time.parse(restart_failure_time).to_i < Time.parse(start_time).to_i)`

**Comment by pu239ppy** [comment]
Closing as PR merged
