### ISSUE TITLE
node search: environment attributes not available in helper methods

### ISSUE THREAD

**Issue by aespinosa** [bloomberg/chef-bach#1139]
Adding this change to aid in debugging:

```
diff --git a/lib/cluster-def-gem/lib/cluster_def.rb b/lib/cluster-def-gem/lib/cluster_def.rb
index a37260d..991de0f 100644
--- a/lib/cluster-def-gem/lib/cluster_def.rb
+++ b/lib/cluster-def-gem/lib/cluster_def.rb
@@ -84,6 +84,7 @@ module BACH
         end
         # validate node ids
         if (cluster_def.select{ |row| validate_node_number?(row[:node_id]) == false }).length.positive?  then
+          puts cluster_def
           fail "Retreived cluster data appears to be invalid -- node IDs must be positive integers between 0 and 256 (1..255)"
         end
     end

```

Currently getting the following error:

```
d/75-persistent-net-generator.rules", "preferred_disk_drivers"=>["ahci"], "early_command"=>"  udevadm trigger; udevadm settle --timeout=30 ; \\\n  set -- $(vgs --rows --noheadings | head -n 1); \\\n  for vg in \"$@\"; do \\\n    echo Removing volume group $vg \\\n      >> /tmp/early_command.out; \\\n    lvm vgremove -f \"$vg\" \\\n      >> /tmp/early_command.out; \\\n  done; \\\n  for d in `ls /dev/sd[a-z]*`; do \\\n    echo Removing LVM PVs from $d \\\n      >> /tmp/early_command.out 2>&1; \\\n    lvm pvremove -f $d \\\n      >> /tmp/early_command.out 2>&1; \\\n    echo Erasing first blocks on $d \\\n      >> /tmp/early_command.out 2>&1; \\\n    dd if=/dev/zero of=$d bs=64M count=16 \\\n      >> /tmp/early_command.out 2>&1; \\\n  done\n"}, "admin_users"=>[], "interface"=>"eth0", "pxe_interface"=>"eth1", "server"=>"10.0.100.3", "vip"=>"10.0.100.3", "dhcp_range"=>"10.0.100.14 10.0.100.250", "dhcp_subnet"=>"10.0.100.0", "proxy"=>"http://devproxy.bloomberg.com:82", "hostname"=>"bcpc-bootstrap"}
http://10.0.100.3
Retreived cluster data appears to be invalid -- node IDs must be positive integers between 0 and 256 (1..255)
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/cluster_def-0.1.0/lib/cluster_def.rb:88:in `validate_cluster_def'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/cluster_def-0.1.0/lib/cluster_def.rb:112:in `parse_cluster_def'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/cluster_def-0.1.0/lib/cluster_def.rb:140:in `fetch_cluster_def_http'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/cluster_def-0.1.0/lib/cluster_def.rb:124:in `fetch_cluster_def'
/var/chef/cache/cookbooks/bcpc/libraries/utils.rb:193:in `fetch_all_nodes'
/var/chef/cache/cookbooks/bcpc/libraries/utils.rb:232:in `get_head_nodes'
/var/chef/cache/cookbooks/bcpc/recipes/mysql.rb:219:in `from_file'
```

`node['bcpc']['boostrap']['cluster_def_path']` is not being populated when the URL for the cluster-definition is being generated from the ruby gem class `BACH::ClusterDef`

made sure the attribute is there in my environment:

```
knife environment show Test-Laptop
chef_type:           environment
...
json_class:          Chef::Environment
name:                Test-Laptop
override_attributes:
  bcpc:
    bootstrap:
      cluster_def_path: /cluster-def/

```

**Comment by aespinosa** [comment]
got it working. forgot to upload my environment.

oops
