### ISSUE TITLE
VM Cluster build fails

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#1154]
With the recent change with node search to rely on ``cluster.txt`` instead of ``chef search``, we will get details about ``headnodes`` from ``get_head_nodes`` call even though there is no node object for the node in ``chef``. This is resulting in VM build failure [here](https://github.com/bloomberg/chef-bach/blob/8199e680af41af9a6c47be2a53d5c71115367c65/cookbooks/bcpc/recipes/certs.rb#L76-L81). The error being
```
================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/bcpc/recipes/certs.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `[]' for nil:NilClass

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/bcpc/recipes/certs.rb:76:in `block in from_file'
    /var/chef/cache/cookbooks/bcpc/recipes/certs.rb:75:in `each'
    /var/chef/cache/cookbooks/bcpc/recipes/certs.rb:75:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/bcpc/recipes/certs.rb:

   69:  # the DNS and IP lists includes
   70:  # 1. the global virtual IP and cluster virtual hostname
   71:  # 2. head nodes machine IP and hostnames
   72:  ip_list = [node['bcpc']['management']['vip']]
   73:  dns_list = [node['bcpc']['management']['viphost']]
   74:  headnodes = get_head_nodes
   75:  headnodes.each do |hh|
   76>>   ip = hh['bcpc']['management']['ip']
   77:    ip_list.push(ip) unless ip.nil?
   78:    fqdn = hh['fqdn']
   79:    dns_list.push(fqdn) unless fqdn.nil?
```

**Comment by vt0r** [comment]
Fixed by #1155
