### ISSUE TITLE
nil:NilClass seen in wait_for_hosts.rb

### ISSUE THREAD

**Issue by vt0r** [bloomberg/chef-bach#1157]
Seeing the following while `wait_for_hosts.rb` is running on current master. Will try to edit this comment with better debug information as soon as possible.

```
Searching for installed hosts, attempt 1/120
undefined method `[]' for nil:NilClass
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:135:in `fetch_cluster_def_http'
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:123:in `fetch_cluster_def'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:137:in `listening_hosts'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:155:in `block in <top (required)>'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `each'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/chefdk/embedded/bin/bundle:22:in `load'
/opt/chefdk/embedded/bin/bundle:22:in `<main>'
	Booted hosts from apache log (3/3):
		10.0.100.11: stage-3
		10.0.100.12: stage-3
		10.0.100.13: stage-3

	Completed installations from apache log (0/3):
		

	Installed hosts that are listening for SSH on port 22 (0/3):
		

	Hosts still missing (3/3):
		bcpc-vm1, bcpc-vm2, bcpc-vm3
```

**Comment by leochen4891** [comment]
Got the same error
```
Searching for installed hosts, attempt 105/120
undefined method `[]' for nil:NilClass
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:135:in `fetch_cluster_def_http'
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:123:in `fetch_cluster_def'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:137:in `listening_hosts'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:155:in `block in <top (required)>'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `each'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/chefdk/embedded/bin/bundle:22:in `load'
/opt/chefdk/embedded/bin/bundle:22:in `<main>'
        Booted hosts from apache log (3/3):
                10.0.100.11: stage-3
                10.0.100.12: stage-3
                10.0.100.13: stage-3

        Completed installations from apache log (1/3):
                bcpc-vm1

        Installed hosts that are listening for SSH on port 22 (1/3):
                bcpc-vm1

        Hosts still missing (2/3):
                bcpc-vm2, bcpc-vm3
```

**Comment by http-418** [comment]
I get this from every script that loads cluster_def.  Even loading cluster_def in chef-shell will invoke this.

It doesn't seem to hurt functionality but the exception trace is unwanted spam in our logs.
