### ISSUE TITLE
Need to remove unused zookeeper functions

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#1163]
For e.g. [here](https://github.com/bloomberg/chef-bach/blob/cf690ae7f5da6b9cf240b075bbbc01df8704c32a/cookbooks/bcpc-hadoop/libraries/utils.rb#L219), the code got changed from ``:path`` to ``'path'`` which is not recognized by ``ZooKeeper`` ruby.

**Comment by vt0r** [comment]
Ouch. Looks like a mistake when trying to move from pre- to post-1.9 hash syntax. Should read like this I think:
`path: znode_path, data: node_name`

**Comment by bijugs** [comment]
``:path`` still works, but we have ``'path'`` in quotes which I think never worked.

**Comment by leochen4891** [comment]
@bijugs Do you have an error message?

**Comment by cbaenziger** [comment]
We should have moved to `locking_resource` now. If we can remove these functions too that'd be great! As I recall formatting the HDFS ZKFC znode may use these znode handling functions though.

**Comment by bijugs** [comment]
ran ``zk.create('path' => znode_path, 'data' => node_name)`` manually on ``chef-shell`` and it returns a ``RC`` of ``-8`` which corresponds to ``ZBADARGUMENTS``. The ``chef-bach`` function returns ``false`` as it was an issue with acquiring the lock i.e. creation of ``znode``.

**Comment by leochen4891** [comment]
{code}
chef (12.19.36)> ret = zk.create('path' => znode_path, 'data' => node_name)
Zookeeper::Exceptions::BadArguments: Supported arguments are: [:path, :data, :acl, :ephemeral, :sequence, :callback, :callback_context], but arguments ["path", "data"] were supplied instead
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/client_methods.rb:267:in `assert_keys'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/zookeeper-1.4.11/lib/zookeeper/client_methods.rb:90:in `create'
        from (irb):24
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/shell.rb:75:in `block in start'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/shell.rb:74:in `catch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/shell.rb:74:in `start'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-shell:34:in `<top (required)>'
        from /usr/bin/chef-shell:57:in `load'
        from /usr/bin/chef-shell:57:in `<main>'
{code}
{code}path: znode_path, data: node_name{code} works, thanks Sal

**Comment by cbaenziger** [comment]
So nothing should be calling `acquire_restart_lock` or `zk.create` in Chef-BACH any more -- that should now all be in [`locking_restart`](https://github.com/bloomberg/locking_restart-cookbook); that looks to be orphaned code? The only znode related function still called in Chef-BACH should be [`znode_exists`](https://github.com/bloomberg/chef-bach/blob/23bca917b92d3a2c519411b87e3edbcc6ad4b30f/cookbooks/bcpc-hadoop/recipes/namenode_master.rb#L138).

@bijugs Where are you seeing `zk.create` run?

**Comment by bijugs** [comment]
As I mentioned in my initial comment, if these functions are not used anymore we should remove them and this will be a non issue. It will prevent from any future use as I was trying to use it.

**Comment by cbaenziger** [comment]
Cool! Thanks @bijugs ; I've updated the title to reflect the desired direction and what is up. Yes, let us remove all Zookeeper related functions out of [bcpc](https://github.com/bloomberg/chef-bach/blob/2a713e62996c1b17c37b8e9c943503052c39d673/cookbooks/bcpc-hadoop/libraries/utils.rb#L250-L396)
