### ISSUE TITLE
Fix LZO/GPL compression Library error

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#161]
Currently running a ``map-reduce`` job throws an error akin to 
````
2015-05-28 12:59:54,595 ERROR lzo.GPLNativeCodeLoader (GPLNativeCodeLoader.java:<clinit>(36)) - Could not load native gpl library
java.lang.UnsatisfiedLinkError: no gplcompression in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at com.hadoop.compression.lzo.GPLNativeCodeLoader.<clinit>(GPLNativeCodeLoader.java:32)
        at com.hadoop.compression.lzo.LzoCodec.<clinit>(LzoCodec.java:71)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2015)
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:1980)
        at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:128)
        at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:175)
`````
The links to compression libraries were created as part of PR #23 but they seem to be incorrect.  This need to be fixed for following components:
* ``HBASE-Master``
* ``HBASE-RegionServer``
* ``Hadoop MapReduce``

**Comment by amithkanand** [comment]
This has been resolved with PR #461
