### ISSUE TITLE
Graphite web UI is broken on latest code

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#316]
One a new VM cluster build, noticed that the Graphite Web UI failed to load( HTTP 500). Looking at the logs I see:
```bash
vim /var/log/apache2/error.log...
...
[Mon Oct 26 18:43:01 2015] [error] [client 10.0.100.11] IOError: [Errno 13] Permission denied: '/opt/graphite/storage/log/webapp/info.log'
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11] mod_wsgi (pid=511): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11] mod_wsgi (pid=511): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11] Traceback (most recent call last):
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/conf/graphite.wsgi", line 23, in <module>
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     from graphite.logger import log
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/logger.py", line 87, in <module>
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     log = GraphiteLogger() # import-shared logger instance
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/logger.py", line 40, in __init__
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     level = logging.INFO,
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/logger.py", line 65, in _config_logger
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     handler = Rotater(log_file, when=when, backupCount=backupCount)
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/usr/lib/python2.7/logging/handlers.py", line 65, in __init__
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/usr/lib/python2.7/logging/__init__.py", line 897, in __init__
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     StreamHandler.__init__(self, self._open())
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]   File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11]     stream = open(self.baseFilename, self.mode)
[Mon Oct 26 18:44:01 2015] [error] [client 10.0.100.11] IOError: [Errno 13] Permission denied: '/opt/graphite/storage/log/webapp/info.log'
...
```

The file(s) `/opt/graphite/storage/log/webapp/[info.log, exception.log]` needs to be owned by `www-data`; instead its owned by `root` and so the webapp can't load. There should be some code that makes sure this file exists and can be written to by `www-data`. 
We need to make sure the file is re-created correctly after [this code](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc/recipes/graphite.rb#L229) executes.

Instead of making `www-data` the owner of just that file, we could do `chown -R www-data:www-data /opt/graphite/storage/log/webapp`.

**Comment by cbaenziger** [comment]
I believe there is another issue: `/opt/graphite/webapp/graphite/local_settings.py` is owned by `root:root` and we see the following in `/var/log/apache2/error.log`:
````
[Sun Nov 01 06:59:02 2015] [error] Could not import graphite.local_settings, using defaults!
````

**Comment by kiiranh** [comment]
That was [fixed](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc/recipes/graphite.rb#L176-L180)

**Comment by cbaenziger** [comment]
Thanks; I agree.

**Comment by kiiranh** [comment]
Closing.
