### ISSUE TITLE
Graphite fails to start

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#358]
Spun up a new cluster today evening and graphite fails to start. I see the following the `/var/log/apache2/error.log`:

```bash
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11] mod_wsgi (pid=16058): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11] Traceback (most recent call last):
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 255, in __call__
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     response = self.get_response(request)
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 178, in get_response
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 220, in handle_uncaught_exception
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     if resolver.urlconf_module is None:
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     self._urlconf_module = import_module(self.urlconf_name)
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     __import__(name)
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/urls.py", line 36, in <module>
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     ('^render/?', include('graphite.render.urls')),
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 25, in include
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     urlconf_module = import_module(urlconf_module)
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     __import__(name)
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     from . import views
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]   File "/opt/graphite/webapp/graphite/render/views.py", line 32, in <module>
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11]     from graphite.remote_storage import HTTPConnectionWithTimeout
[Tue Dec 22 18:56:01 2015] [error] [client 10.0.100.11] ImportError: cannot import name HTTPConnectionWithTimeout
```

**Comment by pu239ppy** [comment]
That was fixed, currently the error messages are 
[Thu Jan 07 17:15:05 2016] [error] [client 10.0.100.12] Traceback (most recent call last):
[Thu Jan 07 17:15:05 2016] [error] [client 10.0.100.12]   File "/opt/graphite/conf/graphite.wsgi", line 25, in <module>
[Thu Jan 07 17:15:05 2016] [error] [client 10.0.100.12]     import graphite.metrics.search
[Thu Jan 07 17:15:05 2016] [error] [client 10.0.100.12] ImportError: No module named search
