### ISSUE TITLE
Error During bootstrap

### ISSUE THREAD

**Issue by quasiben** [bloomberg/chef-bach#362]
During a vanilla run of `./vbox_create.sh` I get the following error:

```
+ rm pyparsing-2.0.6.zip
+ fpm --epoch 1450838215 --log info --python-install-bin /opt/graphite/bin -f -s python -t deb pyparsing-2.0.6/setup.py
/var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included': undefined method `options' for #<Cabin::Subscriber:0x7f15d21861b0> (NoMethodError)
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `all?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:90:in `log_with_level'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:75:in `info'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:279:in `execute'
	from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/bin/fpm:8
	from /usr/local/bin/fpm:19:in `load'
	from /usr/local/bin/fpm:19
Connection to 127.0.0.1 closed.
```

OSX 10.10.4
Vagrant 1.7.4

**Comment by http-418** [comment]
Ben, the 'cabin' errors are a red herring.  The log library is crashing, so we're not seeing the real error message.  Something is going wrong at some other point.

I'll see if I can re-create this on my machine.

**Comment by http-418** [comment]
Yep, this is definitely occurring in the Jenkins build.

**Comment by quasiben** [comment]
Cool, thanks for looking into this

**Comment by http-418** [comment]
This particular issue should be fixed.
