### ISSUE TITLE
HBase RegionServer fails to start in secure mode

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#457]
After kerberizing the cluster the `HBase` regionserver fails to start and throws following error:

```
2016-03-30 08:05:42,630 ERROR org.apache.hadoop.hbase.coprocessor.CoprocessorHost: The coprocessor org.apache.hadoop.hbase.security.access.SecureBulkLoadEndpoint threw java.lang.IllegalStateException: Failed to get FileSystem instance
java.lang.IllegalStateException: Failed to get FileSystem instance
        at org.apache.hadoop.hbase.security.access.SecureBulkLoadEndpoint.start(SecureBulkLoadEndpoint.java:153)
        at org.apache.hadoop.hbase.coprocessor.CoprocessorHost$Environment.startup(CoprocessorHost.java:411)
        at org.apache.hadoop.hbase.coprocessor.CoprocessorHost.loadInstance(CoprocessorHost.java:253)
        at org.apache.hadoop.hbase.coprocessor.CoprocessorHost.loadSystemCoprocessors(CoprocessorHost.java:156)
        at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.<init>(RegionCoprocessorHost.java:231)
        at org.apache.hadoop.hbase.regionserver.HRegion.<init>(HRegion.java:723)
        at org.apache.hadoop.hbase.regionserver.HRegion.<init>(HRegion.java:631)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hbase.regionserver.HRegion.newHRegion(HRegion.java:5893)
        at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:6203)
        at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:6175)
        at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:6131)
        at org.apache.hadoop.hbase.regionserver.HRegion.openHRegion(HRegion.java:6082)
        at org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler.openRegion(OpenRegionHandler.java:362)
        at org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler.process(OpenRegionHandler.java:129)
        at org.apache.hadoop.hbase.executor.EventHandler.run(EventHandler.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied. user=hbase is not the owner of inode=tmp
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkOwner(FSPermissionChecker.java:250)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:227)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:190)
```

PR #445 added the logic into [`hbase_master`](https://github.com/cbaenziger/chef-bach/blob/06d0496b68ddebca673fbd23ea6e673c0c6a79a4/cookbooks/bcpc-hadoop/recipes/hbase_master.rb#L51-L59) recipe to create the staging directory required for `SecureBulkLoadEndpoint` but there are couple of issues with that.

* The `/tmp` directory is already created by [`namenode_no_HA`](https://github.com/bloomberg/chef-bach/blob/ca8b6b5cbf82500d74dc5591c77efe568f5fc9fe/cookbooks/bcpc-hadoop/recipes/namenode_no_HA.rb#L137-L141) 
*  PR #445 uses `/tmp` as staging directory for `HBase SecureBulkLoadEndpoint` but resource never converges as directory already exists
* PR #445 tries to set owner/permissions on `/tmp` to `hbase`/`711` which can break other components that need to use `/tmp`
* Looks like `HBase` code expects parent of `staging-directory` to be owned by `HBase` and fails to start with error message mentioned above.

**Comment by amithkanand** [comment]
Resolved in PR #458.
