### ISSUE TITLE
MySQL Error when a new head node is added to an existing cluster - UEFI_SUPPORT Branch

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#666]
I built a 3 (default) node cluster using UEFI_SUPPORT branch. After that I am trying to expand the cluster by adding 1 head node and 2 worker nodes. The 3rd node was added successfully but when I tried chef-ing existing head nodes, head node 2 failed with following error:

```
  * ruby_block[Check MySQL Quorum Status] action run
================================================================================
Error executing action `run` on resource 'ruby_block[Check MySQL Quorum Status]'
================================================================================


RuntimeError
------------
MySQL wsrep status still not ready after 10 poll attempts! (got: nil)


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/bcpc/recipes/mysql.rb:242:in `block (2 levels) in from_file'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/bcpc/recipes/mysql.rb

209: ruby_block 'Check MySQL Quorum Status' do
210:   block do
211:     require 'mysql2'
212:     require 'timeout'
213:
214:     # Returns 'ON' if wsrep is ready.
215:     # Returns 'nil' if we time out or get an error.
216:     def wsrep_ready_value(client_options)
217:       Timeout.timeout(5) do
218:         client = Mysql2::Client.new(client_options)
219:         result = client.query("SHOW GLOBAL STATUS LIKE 'wsrep_ready'")
220:         result.first['Value']
221:       end
222:     rescue
223:       nil
224:     end
225:
226:     mysql_status = nil
227:     poll_attempts = 10
228:
229:     poll_attempts.times do |i|
230:       mysql_status = wsrep_ready_value(mysql_local_connection_info)
231:       if mysql_status == 'ON'
232:         Chef::Log.info("MySQL is up after #{i} poll attempts")
233:         break
234:       else
235:         Chef::Log.debug("MySQL status is #{mysql_status.inspect}, sleeping")
236:         sleep(0.5)
237:       end
238:     end
239:



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/bcpc/recipes/mysql.rb:209:in `from_file'

ruby_block("Check MySQL Quorum Status") do
  action "run"
  retries 0
  retry_delay 2
  guard_interpreter :default   
  block_name "Check MySQL Quorum Status"
  cookbook_name "bcpc"
  recipe_name "mysql"
  block #<Proc:0x00000005b4fb68@/var/chef/cache/cookbooks/bcpc/recipes/mysql.rb:210>
end
```

**Comment by amithkanand** [comment]
Trying to chef the 2nd head node once again.

**Comment by amithkanand** [comment]
Looking at 2nd head node, MySQL service is stopped. I am not sure why would this happen on a running cluster:
```
root@bcpc-vm2:/home/ubuntu# cd
root@bcpc-vm2:~# service mysql status
 * MySQL (Percona XtraDB Cluster) is stopped. Check log
```

Also, since now I have 3 head nodes, not sure why quorum is not found.

**Comment by amithkanand** [comment]
Started `MySQL` service manually and re-chef'd the node again.  This time `chef-client` ran successfully. It would be good to reproduce/investigate why `MySQL` went down.
