### ISSUE TITLE
1.7.1 VM cluster fails to build due to hbase changes

### ISSUE THREAD

**Issue by http-418** [bloomberg/chef-bach#671]
Additionally, we appear to still be using node.set where we should not be

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_master.rb
================================================================================


NoMethodError
-------------
undefined method `+' for nil:NilClass


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_config.rb:166:in `from_file'
  /var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_master.rb:3:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_config.rb:

159:    mode 0644
160:    variables(:options => complete_hbase_site_hash)
161:  end
162:  
163:  if node[:bcpc][:hadoop][:kerberos][:enable] == true then
164:      node.set['bcpc']['hadoop']['hbase']['env']['HBASE_OPTS'] = 
165:        node['bcpc']['hadoop']['hbase']['env']['HBASE_OPTS'] +
166>>       ' -Djava.security.auth.login.config=/etc/hbase/conf/hbase-client.jaas'
167:      node.set['bcpc']['hadoop']['hbase']['env']['HBASE_MASTER_OPTS'] =
168:        node['bcpc']['hadoop']['hbase']['env']['HBASE_MASTER_OPTS'] + 
169:        ' -Djava.security.auth.login.config=/etc/hbase/conf/hbase-server.jaas'
170:      node.set['bcpc']['hadoop']['hbase']['env']['HBASE_REGIONSERVER_OPTS'] =
171:        node['bcpc']['hadoop']['hbase']['env']['HBASE_REGIONSERVER_OPTS'] + 
172:        ' -Djava.security.auth.login.config=/etc/hbase/conf/regionserver.jaas'
173:  end
174:  
175:  #
```

**Comment by http-418** [comment]
This is remedied by the changes Esther merged the other day.
