### ISSUE TITLE
bcpc_jmxtrans::default returns invalid date

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#69]
On a number of physical clusters we are seeing:
````
  * service[restart jmxtrans on dependent service manual restart] action restart
================================================================================
Error executing action `restart` on resource 'service[restart jmxtrans on dependent service manual restart]'
================================================================================


ArgumentError
-------------
invalid date


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:50:in `parse'
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:50:in `block (2 levels) in process_require_restart?'
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:48:in `each'
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:48:in `block in process_require_restart?'
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:44:in `each'
/var/chef/cache/cookbooks/bcpc_jmxtrans/libraries/utils.rb:44:in `process_require_restart?'
/var/chef/cache/cookbooks/bcpc_jmxtrans/recipes/default.rb:88:in `block (2 levels) in from_file'
````

**Comment by cbaenziger** [comment]
Instrumenting the exception I see the issue:
````invaid data target process: 20:19
, dependent process:  2014````

We need to expect all variants of ps's semantics; or pick a format which does not change. From `ps`(1) I see for `start_time`:
````
start_time  START     starting time or date of the process.  Only the year will be displayed if the process was not started the same year ps was invoked, or "MmmDD" if it was not started the same day, or "HH:MM" otherwise.  See also bsdstart, start, lstart, and stime.
````

I think `lstart` would be a better field choice, as it returns strings like `Fri Aug  8 12:15:42 2014`
Sadly, its entry in `ps`(1) is not quite descriptive of its return though:
`time the command started.`
