### ISSUE TITLE
Unable to chef worker nodes after 2.1.2 upgrade.

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#757]
I am getting below error when I try to chef worker nodes after upgrading them to 2.1.2 release. 
```
================================================================================
Error executing action `create` on resource 'ruby_block[handle_prev_hbase_regionserver_restart_failure]'
================================================================================

ArgumentError
-------------
argument out of range

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:379:in `block in process_start_time'
/var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:377:in `each'
/var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:377:in `process_start_time'
/var/chef/cache/cookbooks/bcpc-hadoop/libraries/utils.rb:394:in `process_restarted_after_failure?'
/var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:38:in `block (3 levels) in from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb

 32:     ruby_block "handle_prev_#{params[:service_name].gsub('-','_')}_restart_failure" do
 33:       block do
 34:         Chef::Log.info "Need to restart #{params[:service_name]} since it failed during the previous run. Another node's restart process failure is a possible reason"
 35:       end
 36:       action :create
 37:       only_if { node[:bcpc][:hadoop][params[:service_name].gsub('-','_').to_sym][:restart_failed] and 
 38:               !process_restarted_after_failure?(node[:bcpc][:hadoop][params[:service_name].gsub('-','_').to_sym][:restart_failed_time],"#{params[:process_identifier]}")}
 39:     end
 40:     #

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:32:in `block in from_file'

ruby_block("handle_prev_hbase_regionserver_restart_failure") do
  params {:service_name=>"hbase-regionserver", :dependencies=>["template[/etc/hbase/conf/hadoop-metrics2-hbase.properties]", "template[/etc/hbase/conf/hbase-site.xml]", "template[/etc/hbase/conf/hbase-env.sh]", "template[/etc/hbase/conf/hbase-policy.xml]", "template[/etc/hadoop/conf/log4j.properties]", "template[/etc/hadoop/conf/hdfs-site.xml]", "template[/etc/hadoop/conf/core-site.xml]", "bash[hdp-select hbase-regionserver]", "user_ulimit[hbase]", "log[jdk-version-changed]"], :process_identifier=>"org.apache.hadoop.hbase.regionserver.HRegionServer", :name=>"hbase-regionserver"}
  action [:create]
  retries 0
  retry_delay 2
  guard_interpreter :default
  block_name "handle_prev_hbase_regionserver_restart_failure"
  cookbook_name "bcpc-hadoop"
  recipe_name "region_server"
  block #<Proc:0x00000005a2f8a0@/var/chef/cache/cookbooks/bcpc-hadoop/definitions/hadoop_service.rb:33>
  only_if { #code block }
end

Recipe: sysctl::default
  * ruby_block[save-sysctl-params] action run
    - execute the ruby block save-sysctl-params

  * template[/etc/sysctl.d/99-chef-attributes.conf] action create (up to date)

Running handlers:
  - GraphiteReporting
Running handlers complete

Chef Client failed. 61 resources updated in 131.35821073 seconds
```

**Comment by vt0r** [comment]
Fixed already in #754
