### ISSUE TITLE
Re-running tests/automated_install.sh is not idempotent

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#871]
While `automated_install.sh` should be idempotent, it is failing in Master right now. One will see the following failure on a re-run:

```
+ printf '#### Chef the nodes with Basic role\n'
#### Chef the nodes with Basic role
+ vagrant ssh -c 'cd chef-bcpc; ./cluster-assign-roles.sh Test-Laptop Basic'
You are replacing the current local value of PATH, which is currently "/home/vagrant/chef-bcpc/vendor/bundle"
[...]
bundler: failed to load command: ./cluster_assign_roles.rb (./cluster_assign_roles.rb)
ArgumentError: Missing value for required option(s): ''client_name''
  /home/vagrant/chef-bcpc/vendor/bundle/ruby/2.3.0/gems/ridley-5.1.0/lib/ridley/client.rb:57:in `validate_options'
[...]
  /home/vagrant/chef-bcpc/lib/cluster_data.rb:192:in `block in ridley'
  /home/vagrant/chef-bcpc/lib/cluster_data.rb:192:in `chdir'
  /home/vagrant/chef-bcpc/lib/cluster_data.rb:192:in `ridley'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:433:in `car_cli'
  /home/vagrant/chef-bcpc/cluster_assign_roles.rb:486:in `<top (required)>'
E, [2017-06-04T23:29:38.302673 #28642] ERROR -- : Actor crashed!
ArgumentError: Missing value for required option(s): ''client_name''
```

Then, if logging into the Bootstrap VM one will see:
```
cbaenzig@clay-desktop:/data/chef-bach$ vagrant ssh
[...]
vagrant@bcpc-bootstrap:~$ cd chef-bcpc
vagrant@bcpc-bootstrap:~/chef-bcpc$ knife node list
/opt/chef/embedded/lib/ruby/2.3.0/open-uri.rb:37:in `initialize': Permission denied @ rb_sysopen - /var/log/chef/client.log (Errno::EACCES)
 [...]
vagrant@bcpc-bootstrap:~/chef-bcpc$ ls -l .chef/
total 100
-r-xr-x--- 1 vagrant root  1679 Jun  2 17:44 bcpc-bootstrap.bcpc.example.com.pem
-rw-r--r-- 1 root    root   333 Jun  4 23:16 knife.rb
drwxrwx--- 2 vagrant root 90112 Jun  2 17:43 syntax_check_cache
[...]
vagrant@bcpc-bootstrap:~/chef-bcpc$ cat .chef/knife.rb 
chef_server_url "https://10.0.100.3"
client_fork true
log_location "/var/log/chef/client.log"
ssl_verify_mode :verify_none
validation_client_name "chef-validator"
verify_api_cert false
# Using default node name (fqdn)



# Do not crash if a handler is missing / not installed yet
begin
rescue NameError => e
  Chef::Log.error e
end
vagrant@bcpc-bootstrap:~/chef-bcpc$ sudo knife node list
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable
vagrant@bcpc-bootstrap:~/chef-bcpc$ sudo knife node list -c .chef/knife.rb 
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable
vagrant@bcpc-bootstrap:~/chef-bcpc$ sudo knife node list -c .chef/knife.rb -k .chef/bcpc-bootstrap.bcpc.example.com.pem -u `hostname -f`
bcpc-bootstrap.bcpc.example.com
bcpc-vm1.bcpc.example.com
bcpc-vm2.bcpc.example.com
bcpc-vm3.bcpc.example.com
```

I believe @amithkanand may have seen this in slightly different guise?

**Comment by aespinosa** [comment]
#896   fixes this

**Comment by cbaenziger** [comment]
Fixed!
