### ISSUE TITLE
Java install fails in bcpc-hadoop::configs

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#877]
From here https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/configs.rb#L71 calls `include_recipe "java::default"`

````
    ================================================================================
    Error executing action `install` on resource 'java_ark[jdk]'
    ================================================================================

    SystemExit
    ----------
    exit

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/java/providers/ark.rb:176:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/java/providers/ark.rb:145:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/java/recipes/oracle.rb

     61: java_ark 'jdk' do
     62:   url tarball_url
     63:   default node['java']['set_default']
     64:   checksum tarball_checksum
     65:   app_home java_home
     66:   bin_cmds bin_cmds
     67:   alternatives_priority node['java']['alternatives_priority']
     68:   retries node['java']['ark_retries']
     69:   retry_delay node['java']['ark_retry_delay']
     70:   connect_timeout node['java']['ark_timeout']
     71:   use_alt_suffix node['java']['use_alt_suffix']
     72:   reset_alternatives node['java']['reset_alternatives']
     73:   download_timeout node['java']['ark_download_timeout']
     74:   proxy node['java']['ark_proxy']
     75:   action :install
     76:   notifies :write, 'log[jdk-version-changed]', :immediately
     77: end
     78:
     79: if node['java']['set_default'] && platform_family?('debian')
     80:   include_recipe 'java::default_java_symlink'
     81: end
     82:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:61:in `from_file'

    java_ark("jdk") do
      action [:install]
      supports {:report=>true, :exception=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :java_ark
      cookbook_name "java"
      recipe_name "oracle"
      url "http://10.0.100.3/jdk-linux-x64.tar.gz"
      default true
      checksum "62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236"
      app_home "/usr/lib/jvm/java-8-oracle-amd64"
      bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jdeps", "jhat", "jinfo", "jjs", "jmap", "jmc", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
      alternatives_priority 1062
      connect_timeout 600
      use_alt_suffix true
      reset_alternatives true
      download_timeout 600
      owner "root"
    end

    Platform:
    ---------
    x86_64-linux
````

**Comment by pu239ppy** [comment]
This may be chef 12 related

**Comment by pu239ppy** [comment]
Will try old cookbook version with URL overrides from 1.50

**Comment by pu239ppy** [comment]
Attempted to go bach to 1.48.0 and override attributes so it finds modern the correct Java URL, but still with the same result, however I found this in the log
````
Further information in the log
```
[2017-06-10T22:19:04-04:00] INFO: template[/etc/profile.d/jdk.sh] created file /etc/profile.d/jdk.sh
[2017-06-10T22:19:04-04:00] INFO: template[/etc/profile.d/jdk.sh] updated file contents /etc/profile.d/jdk.sh
[2017-06-10T22:19:04-04:00] INFO: template[/etc/profile.d/jdk.sh] mode changed to 755
[2017-06-10T22:19:04-04:00] INFO: Processing apt_package[tar] action install (java::oracle line 55)
[2017-06-10T22:19:04-04:00] INFO: Processing java_ark[jdk] action install (java::oracle line 59)
[2017-06-10T22:19:04-04:00] INFO: Adding jdk to /usr/lib/jvm/jdk1.6.0
[2017-06-10T22:19:04-04:00] INFO: Processing remote_file[/var/chef/cache/jdk-linux-x64.tar.gz] action create_if_missing (/var/chef/cache/cookbooks/java/providers/ark.rb line 130)
[2017-06-10T22:19:10-04:00] INFO: remote_file[/var/chef/cache/jdk-linux-x64.tar.gz] created file /var/chef/cache/jdk-linux-x64.tar.gz
[2017-06-10T22:19:10-04:00] INFO: remote_file[/var/chef/cache/jdk-linux-x64.tar.gz] updated file contents /var/chef/cache/jdk-linux-x64.tar.gz
[2017-06-10T22:19:11-04:00] INFO: remote_file[/var/chef/cache/jdk-linux-x64.tar.gz] mode changed to 755
[2017-06-10T22:19:14-04:00] FATAL:  Command ' mv "/var/chef/cache/jdk1.6.0" "/usr/lib/jvm/jdk1.6.0" ' failed
```

**Comment by pu239ppy** [comment]
Looks like in java cook book attributes the default version is quoted, tried quoting in bcpc-hadoop/attributes/default.rb and even fixing the default in java cookbook and re-uploading and still did not work.

**Comment by pu239ppy** [comment]
I think the java_ark provider attempts to parse the archive filename to figure out the java major and update versions since we now use a generic name it is unable to make the determination

**Comment by cbaenziger** [comment]
Indeed it does that here: https://github.com/agileorbit-cookbooks/java/blob/master/providers/ark.rb#L28-L50
I'll issue a PR to fix this...

**Comment by cbaenziger** [comment]
Indeed it does that here: https://github.com/agileorbit-cookbooks/java/blob/master/providers/ark.rb#L28-L50
I'll issue a PR to fix this...
